name: Deploy to npm

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node:latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_CONFIG_REGISTRY: https://registry.npmjs.org/

    steps:

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install

      - name: Prepare environment
        run: pnpm run dev:prepare

      - name: Run linter
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

      # - name: Run tests
      #   run: pnpm run test

      # - name: Build Vue fixture tests
      #   run: pnpm run test:vue

      - name: Build project
        run: pnpm run build

      - name: Build Vue fixture
        run: pnpm run test:vue:build

      - name: Publish to npm
        run: pnpx pkg-pr-new publish --compact --no-template --pnpm && pnpm publish
